#!/bin/bash

if ! command -v xbacklight; then
  exit 0
fi

value=$(printf "%.0f" $(xbacklight -get))

case $1 in
  up)
    value=$((value + 10))
    ;;
  down)
    value=$((value - 10))
    ;;
esac

notify-send -i display \
  -h int:value:$value \
  -h string:synchronous:backlight \
  "Backlight: $value%"
xbacklight -set $value
